/*
 gpu64: the Commodore 64 character ROM as gpu64's HDMI font.

 The data lives in gpu64_c64font.cpp, generated by tools/gen_c64font.py from
 a 901225-01 chargen dump; this is the handle everything that paints text on
 HDMI uses -- the boot wordmark and the on-screen log in graphics mode, every
 cell of the 80x50 text mode, and the mirrored C64 screen.

 Indexing is by *screen code*, not by ASCII: code 1 is 'A' in charset 0 and
 'a' in charset 1, exactly as a POKE to $0400 behaves on the C64 itself. Text
 arriving from the firmware's own C strings goes through
 gpu64_c64ScreenCode() first.
*/
#ifndef _gpu64_c64font_h
#define _gpu64_c64font_h

#include <circle/types.h>

// The two ROM halves: 0 = uppercase/graphics, 1 = lowercase/uppercase.
#define GPU64_CHARSET_UPPER	0
#define GPU64_CHARSET_LOWER	1
#define GPU64_CHARSET_COUNT	2

// [charset][screen code][row], row 0 topmost, bit 7 leftmost.
extern const u8 gpu64C64Font[ GPU64_CHARSET_COUNT ][ 256 ][ 8 ];
extern const u8 gpu64C64AsciiToScreen[ GPU64_CHARSET_COUNT ][ 128 ];

// ASCII (or a plain C string byte) to the screen code that draws it in the
// given charset. Bytes >= 0x80 have no ASCII meaning here and come back as a
// space rather than as an arbitrary reverse-video glyph.
static inline u8 gpu64_c64ScreenCode( char c, u8 nCharset )
{
	u8 b = (u8)c;
	if ( b >= 0x80 )
		return 0x20;
	return gpu64C64AsciiToScreen[ nCharset & 1 ][ b ];
}

#endif
